id: I97B90DC0
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-24
  title: བདེ་མཆོག་གི་ཟིན་བྲིས་གཅེས་བཏུས།
  author: མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།, མཛད་པ་པོ། ཀརྨ་ཚེ་དབང་ཀུན་ཁྱབ།, མཛད་པ་པོ།
    དཀོན་མཆོག་བསྟན་འཛིན།
  authors: &id001
  - མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།
  - མཛད་པ་པོ། ཀརྨ་ཚེ་དབང་ཀུན་ཁྱབ།
  - མཛད་པ་པོ། དཀོན་མཆོག་བསྟན་འཛིན།
  sku: RDI-KK-24
  cover: RDI-KK-24.jpeg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: བདེ་མཆོག་གི་ཟིན་བྲིས་གཅེས་བཏུས།
  authors: *id001
  sku: RDI-KK-24
  cover: RDI-KK-24.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- Tsawa
- Yigchung
